In [2]:
import numpy as np
# 里面的数据结构只有一种，即ndarray(n-dimensional array)

In [3]:
import random
import time
a = []
for i in range(100000000):
    a.append(random.random())
# 生成一亿个随机[0, 1)浮点数
t1 = time.time()
sum1 = sum(a)
t2 = time.time()
b = np.array(a)
t3=time.time()
sum2 = np.sum(b)
t4 = time.time()
print(f'Python:{t2 - t1}, Numpy:{t4 - t3}')
# 使用Numpy计算大量数据效率远胜于纯Python

Python:1.4563791751861572, Numpy:0.17255878448486328


一维数组

In [4]:
list1 = [1, 2, 3, 4, 5]
oneArray = np.array(list1)
print(type(oneArray))
print(oneArray)
# 这就创建了一个ndarray

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [5]:
# 创建ndarray有三种方式
# 1.直接传入列表
t1 = np.array([1, 2, 3, 4, 5])
print(type(t1))
print(t1)
# 2.使用range()
# 遍历了range(), 再复制到ndarray中
t2 = np.array(range(1, 6))
print(type(t2))
print(t2)
# 3.使用np.arange(), 直接创建ndarray, arange支持浮点步长
t3 = np.arange(0, 10, 2)
print(type(t3))
print(t3)

<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
[0 2 4 6 8]


二维数组

In [6]:
list2 = [[1, 2, 3], [4, 5, 6]]
twoArray = np.array(list2)  # 将二维的列表传入就创建了二维的ndarray
print(twoArray)

[[1 2 3]
 [4 5 6]]


常用数组属性

In [7]:
list3 = [[1,2],[3,4],[5,6]]
array = np.array(list3)
print(array.ndim)
# 数组的维度
print(array.shape)
# 数组的形状
print(array.size)
# 数组元素个数

2
(3, 2)
6


# 调整数组形状

In [8]:
list4 = np.array([[1,2,3],[4,5,6]])
list4.shape = (3,2)
# 将2行3列变成3行2列
print(list4)

[[1 2]
 [3 4]
 [5 6]]


In [11]:
list4 = np.array([[1,2,3],[4,5,6]])
print(f'id of list4:{id(list4)}')
list4.shape = (3,2)
# 修改了原来的数组
print(f'id of list4:{id(list4)}')
print(list4)
list5 = list4.reshape(3,2)
# 返回一个新的数组
print(f'id of list5:{id(list5)}')
print(list5)

id of list4:2113529661264
id of list4:2113529661264
[[1 2]
 [3 4]
 [5 6]]
id of list5:2113529660784
[[1 2]
 [3 4]
 [5 6]]


In [13]:
list6 = list4.reshape((6,),order='C')
# 将数组展开
# C表示按行优先，F表示按列优先,分别代表C语言风格和Fortran风格
print(list6)

[1 2 3 4 5 6]


In [15]:
list7 = list4.flatten(order='C')
# 另一种展开的方法
print(list7)

[1 2 3 4 5 6]


In [18]:
t = np.arange(24)
print(t)
print(t.shape)
t1 = t.reshape((2,3,4))
# reshape方法还有其他参数,所以要两层括号
# 从外到内的方括号分别代表0轴,1轴,2轴,分别是2维,3维,4维
print(t1)
print(t1.shape)
t2 = t1.reshape((24, ))
# 展开会恢复原来的样子
print(t2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


# 转换成列表

In [19]:
a= np.array([9, 12, 88, 14, 25])
list_a = a.tolist()
print(list_a)
print(type(list_a))

[9, 12, 88, 14, 25]
<class 'list'>


# 数据类型

In [21]:
f = np.array([1,2,3,4,5], dtype = np.int16)
print(f.itemsize)
# 指定元素类型, 所以一个元素占2字节
print(f.dtype)
# 获取数据类型
f1 = f.astype(np.int64)
# 调整数据类型
print(f1.dtype)

2
int16
int64


In [23]:
print(round(random.random(),2))
arr = np.array([random.random() for i in range(10)])
# 取小数点后两位
print(np.round(arr,2))
print(arr.dtype)

0.67
[0.95 0.14 0.53 0.89 0.6  0.16 0.96 0.83 0.95 0.68]
float64


# 数组的计算

In [28]:
print([1, 2, 3]+[4, 5, 6])
# 列表的默认行为是拼接数组, 且不能列表+int
t1 =np.arange(24).reshape((6,4))
print(t1+2)
# 每个元素都加了2(广播机制))
print("-"*20)
print(t1*2)
print("-"*20)
print(t1/2)
# 输出就算是整数也带小数点,说明是浮点类型的

[1, 2, 3, 4, 5, 6]
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


In [34]:
t1 = np.arange(24).reshape((6,4))
t2 = np.arange(100,124).reshape((6,4))
# 要进行运算, 两个数组必须至少有一个维度相同, 如果不是所有维度都相同,必须只有一个维度相同,其他为1
print(t1)
print(t2)
print("-"*20)
print(t1+t2)
print("-"*20)
print(t1*t2)
# 逐元素相乘

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
--------------------
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
--------------------
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


In [33]:
t1 = np.arange(24).reshape((4,6))
t2 = np.arange(0,6).reshape((1,6))
print(t1)
print(t2)
print('-'*20)
print(t1+t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0 1 2 3 4 5]]
--------------------
[[ 0  2  4  6  8 10]
 [ 6  8 10 12 14 16]
 [12 14 16 18 20 22]
 [18 20 22 24 26 28]]


# 轴

In [40]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
# 最外层括号的是0轴, 第二层括号是1轴...
print('-'*20)
print(np.sum(a,axis=0)) 
# 沿着轴0相加, 消掉第0维(把0轴对应位置的元素聚合起来)
print(np.sum(a,axis=1)) 
# 沿着轴1相加, 消掉第1维
print(np.sum(a))

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]
21


In [39]:
a=np.arange(60).reshape((3,4,5))
print(a)
b=np.sum(a, axis=0)
print("-"*20)
print(b)
# 0轴的3块聚合起来, 变成4*5的
c=np.sum(a, axis=1)
print("-"*20)
print(c)
d=np.sum(a, axis=2)
print("-"*20)
print(d)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
--------------------
[[ 60  63  66  69  72]
 [ 75  78  81  84  87]
 [ 90  93  96  99 102]
 [105 108 111 114 117]]
--------------------
[[ 30  34  38  42  46]
 [110 114 118 122 126]
 [190 194 198 202 206]]
--------------------
[[ 10  35  60  85]
 [110 135 160 185]
 [210 235 260 285]]


# 索引和切片

In [41]:
a = np.arange(10)
print(a[2:4])
print(a[2:])
print(a[0:10:2])
# 和list操作基本一样,左闭右开

[2 3]
[2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [44]:
t1 = np.arange(24).reshape(4,6)
print(t1)
print('*'*20)
print(t1[1]) 
# 取一行
print('*'*20)
print(t1[1:])
# 取连续的多行
print('*'*20)
print(t1[1:3,:])
# 取连续的多行
print('*'*20)
print(t1[[0,2,3]])
# 取不连续的多行
print('*'*20)
print(t1[[0,2,3],:])
# 取不连续的多行
print('*'*20)
print(t1[:,1])
# 取一列
print('*'*20)
print(t1[:,1:])
# 连续的多列
print('*'*20)
print(t1[:,[0,2,3]])
# 取不连续的多列
print('*'*20)
print(t1[2,3])
# 取某一个值,三行四列
print('*'*20)
print(t1[2:4,3:5])
# 取一块区域
print('*'*20)
print(t1[[1,2], [0,2]])
# 取1行0列和2行2列


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 6  7  8  9 10 11]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 1  7 13 19]
********************
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
********************
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
********************
15
********************
[[15 16]
 [21 22]]
********************
[ 6 14]


# 数值修改

In [51]:
t = np.arange(24).reshape(4,6)
t[1,:]=0
# 修改第一行
t[:,1]=0
# 修改第一列
print(t)
t = np.arange(24).reshape(4,6)
t[1:3,:]=0
t[:,1:3]=0
# 修改多行多列
print(t)
t = np.arange(24).reshape(4,6)
t[[0,1],[2,3]]=0
# 将第0行第2列, 第1行第3列变为0(注意并不是0行1列)
print(t)

[[ 0  0  2  3  4  5]
 [ 0  0  0  0  0  0]
 [12  0 14 15 16 17]
 [18  0 20 21 22 23]]
[[ 0  0  0  3  4  5]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [18  0  0 21 22 23]]
[[ 0  1  0  3  4  5]
 [ 6  7  8  0 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [52]:
t = np.arange(24).reshape(4,6)
t[t>10]=0  # 将所有大于10的元素变为0
print(t)
t = np.arange(24).reshape(4,6)
t[(t > 2) & (t < 6)] = 0  # 将大于2且小于6的
print(t)
t = np.arange(24).reshape(4,6)
t[(t < 2) | (t > 6)] = 0  # 小于2或大于6的
print(t)
t = np.arange(24).reshape(4,6)
t[~(t > 6)] = 0  # 不大于6的
print(t)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]
[[ 0  1  2  0  0  0]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0 0 2 3 4 5]
 [6 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[ 0  0  0  0  0  0]
 [ 0  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [53]:
t=np.arange(24).reshape(4,6)
t=t.clip(10,18)
# 将小于10的元素变为10,大于18的元素变为18, 防止元素过小或过大
print(t)

[[10 10 10 10 10 10]
 [10 10 10 10 10 11]
 [12 13 14 15 16 17]
 [18 18 18 18 18 18]]


三目运算

In [54]:
score = np.array([[80, 88], [82, 81], [75, 81]])
result = np.where(score > 80, True, False)
# 如果大于80则返回True,否则返回False
print(result)

[[False  True]
 [ True  True]
 [False  True]]


# 添加删除和去重

In [65]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print('\n')
print(np.append(a, [7, 8, 9]))
# 不指定轴的话, append会展平双方, 然后按列表添加
print('\n')
print(np.append(a, [[7, 8, 9]], axis=0))
# 沿轴0添加元素, 轴0会增长
print('\n')
print(np.append(a, [[5, 5, 5, 5], [7, 8, 9, 10]], axis=1))
# 轴1会增长

[[1 2 3]
 [4 5 6]]


[1 2 3 4 5 6 7 8 9]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[ 1  2  3  5  5  5  5]
 [ 4  5  6  7  8  9 10]]


In [66]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
print('\n')
# 如果不指定轴会展开
print(np.insert(a, 3, [11, 12]))
print('\n')
# 指定了轴则会广播方式插入
print(np.insert(a, 1, [11], axis=0))
# 在轴0坐标为1的地方, 插入一个长度为2, 元素都为11的数组
print('\n')
print(np.insert(a, 1, 12, axis=1))
# 在轴1坐标为1的地方, 插入一个长度为3, 元素都为12的数组

[[1 2]
 [3 4]
 [5 6]]


[ 1  2  3 11 12  4  5  6]


[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


[[ 1 12  2]
 [ 3 12  4]
 [ 5 12  6]]


In [67]:
a = np.arange(12).reshape(3,4)
print(a)
print('\n')
# 如果不指定轴会展开
print(np.delete(a,5))
print('\n')
# 删除每一行中的1列：
print(np.delete(a,1,axis = 1))
print('\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[ 0  1  2  3  4  6  7  8  9 10 11]


[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]




去重

In [68]:
a = np.array([5,2,6,2,7,5,6,8,2,9])
print (a)
print ('\n')
u = np.unique(a)
# 去重后的数组
print (u)
print ('\n')

[5 2 6 2 7 5 6 8 2 9]


[2 5 6 7 8 9]




In [69]:
u,indices = np.unique(a, return_index = True)
# 每个元素在原数组里的索引
print (indices)
print ('\n')
print (u)
u,indices = np.unique(a,return_inverse = True)
# 返回原数组在去重数组中的下标
print (u)
print (indices)
print ('\n')
u,indices = np.unique(a,return_counts = True)
# 返回去重数组元素的重复次数
print (u)
print (indices)

[1 0 2 4 7 9]


[2 5 6 7 8 9]
[2 5 6 7 8 9]
[1 0 2 0 3 1 2 4 0 5]


[2 5 6 7 8 9]
[3 2 2 1 1 1]


数学计算

In [72]:
score = np.array([[80,88],[82,81],[75,81]])

result = np.max(score)
# 获取所有数据最大值
print(result)

result = np.max(score,axis=0)
# 获取某一个轴上的数据最大值, 轴0消失, 只留下轴0每列最大值
print(result)

result = np.min(score)
# 获取最小值
print(result)
print()
result = np.min(score,axis=0)
# 获取某一个轴上的数据最小值, 轴0消失, 只留下轴0每列最小值
print(result)
# 数据的比较
result = np.maximum([-2, -1, 0, 1, 2], 0) 
# 第一个参数中的每一个数与第二个参数比较, 返回大的
print(result)
result = np.minimum([-2, -1, 0, 1, 2], 0) 
# 第一个参数中的每一个数与第二个参数比较, 返回小的
print(result)
result = np.maximum([-2, -1, 0, 1, 2], [1, 2, 3, 4, 5])
# 返回每个对应位置上的较大值
print(result)
print()
result = np.mean(score) # 获取所有数据的平均值
print(result)
result = np.mean(score,axis=0) # 获取某一行或者某一列的平均值
print(result)
print()
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
print(arr.cumsum(0))
# 沿着轴0求前缀和, 即0行不变,1行变成与上一行的累加
print(arr.cumsum(1))
# 沿着轴1求前缀和, 即0行不变,1行变成与上一列的累加, 2行变成与之前列的累加

88
[82 88]
75

[75 81]
[0 0 0 1 2]
[-2 -1  0  0  0]
[1 2 3 4 5]

81.16666666666667
[79.         83.33333333]

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]


In [75]:
print(score)
result = np.argmin(score,axis=0)
# 0轴最小值的索引
res=np.min(score,axis=0)
# 0轴最小值
print(result, res)
print()
result = np.std(score,axis=0)
# 0轴标准差
print(result)
result = np.ptp(score,axis=None)
# 所有元素的极差
print(result)

[[80 88]
 [82 81]
 [75 81]]
[2 1] [75 81]

[2.94392029 3.29983165]
13
